In [25]:
from src.feature_engineering import process_raw_dataset
from src.utils import load_csv, save_csv
import pandas as pd

In [26]:
raw_path = "../data/raw/synthetic_raw.csv"   # adjust only if you saved elsewhere
df_raw = load_csv(raw_path)
# --- FIX: ensure ts column is datetime ---
df_raw["ts"] = pd.to_datetime(df_raw["ts"])
print("Rows:", len(df_raw))
df_raw.head()

Rows: 4385

,ts,trip_id,lat,lon,speed,accel_x,accel_y,gyro_z,vibration,engine_on,label
0,2025-11-27 15:49:43.058601,0,12.900993,80.099723,0.295863,-0.157236,-0.067257,-0.036365,0.012954,0,0
1,2025-11-27 15:49:44.058601,0,12.900995,80.099723,0.209449,0.023190,0.301501,-0.015137,0.030461,0,0
2,2025-11-27 15:49:45.058601,0,12.900997,80.099723,0.160829,0.186622,0.265479,-0.117088,0.004683,0,0
3,2025-11-27 15:49:46.058601,0,12.900998,80.099723,0.092858,0.366334,-0.155156,-0.082996,0.004683,0,0
4,2025-11-27 15:49:47.058601,0,12.901000,80.099723,0.244139,-0.251109,-0.106614,-0.011673,0.031584,0,0

In [ ]:
raw_path = "../data/raw/synthetic_raw.csv"   # adjust only if you saved elsewhere
df_raw = load_csv(raw_path)
# --- FIX: ensure ts column is datetime ---
df_raw["ts"] = pd.to_datetime(df_raw["ts"])
print("Rows:", len(df_raw))
df_raw.head()

In [27]:
# basic checks
print("Columns:", df_raw.columns.tolist())
print("Missing ts:", df_raw['ts'].isnull().sum())
print("Label distribution:", df_raw['label'].value_counts(dropna=False).to_dict())

Columns: ['ts', 'trip_id', 'lat', 'lon', 'speed', 'accel_x', 'accel_y', 'gyro_z', 'vibration', 'engine_on', 'label']
Missing ts: 0
Label distribution: {0: 4324, 1: 61}

In [28]:
# window_size and step_size are in seconds
df_windows = process_raw_dataset(df_raw, window_size=10, step_size=5)
df_windows = df_windows.reset_index(drop=True)
df_windows.head()

,t_mid,speed_mean,speed_std,accel_mean,accel_std,vib_mean,engine_ratio,gps_jump_mean,label
0,2025-11-27 15:49:48.058601,0.206232,0.082677,0.227599,0.135005,0.013854,0.0,0.196476,0
1,2025-11-27 15:49:53.058601,0.212603,0.076122,0.189858,0.119902,0.016328,0.0,0.213699,0
2,2025-11-27 15:49:58.058601,0.174061,0.105248,0.181871,0.094752,0.019563,0.0,0.169342,0
3,2025-11-27 15:50:03.058601,0.155501,0.112252,0.146645,0.087103,0.015249,0.0,0.171309,0
4,2025-11-27 15:50:08.058601,0.149673,0.092410,0.158080,0.068832,0.014041,0.0,0.161341,0

In [29]:
os.makedirs("../data/processed", exist_ok=True)
save_csv(df_windows, "../data/processed/features.csv")
print("Saved:", "../data/processed/features.csv")

Saved: ../data/processed/features.csv

In [30]:
import os
print("Processed files:", os.listdir("../data/processed"))
pd.read_csv("../data/processed/features.csv").head()

Processed files: ['features.csv']

,t_mid,speed_mean,speed_std,accel_mean,accel_std,vib_mean,engine_ratio,gps_jump_mean,label
0,2025-11-27 15:49:48.058601,0.206232,0.082677,0.227599,0.135005,0.013854,0.0,0.196476,0
1,2025-11-27 15:49:53.058601,0.212603,0.076122,0.189858,0.119902,0.016328,0.0,0.213699,0
2,2025-11-27 15:49:58.058601,0.174061,0.105248,0.181871,0.094752,0.019563,0.0,0.169342,0
3,2025-11-27 15:50:03.058601,0.155501,0.112252,0.146645,0.087103,0.015249,0.0,0.171309,0
4,2025-11-27 15:50:08.058601,0.149673,0.092410,0.158080,0.068832,0.014041,0.0,0.161341,0